database_url: sqlite:////var/folders/4x/q8y1hw0j4zg75lpz9bfyt_3c0000gn/T/tmpl8q1caul.db
tables:
- methods:
  - GET
  - POST
  - PUT
  - DELETE
  name: users
- methods:
  - GET
  - POST
  - PUT
  name: products
- methods:
  - GET
  name: categories
- methods:
  - GET
  - POST
  name: orders
- methods:
  - GET
  - POST
  name: order_items
- methods:
  - GET
  name: audit_logs
