database_url: sqlite:////var/folders/4x/q8y1hw0j4zg75lpz9bfyt_3c0000gn/T/tmpalx71xe3.db
enable_swagger: true
swagger_title: Minimal Store API
swagger_version: 1.0.0
tables:
- crud:
  - get
  - post
  name: products
- crud:
  - get
  name: categories
- crud:
  - post
  name: orders
