database_url: sqlite:////var/folders/4x/q8y1hw0j4zg75lpz9bfyt_3c0000gn/T/tmpalx71xe3.db
enable_swagger: true
swagger_description: Simple store API with basic CRUD operations
swagger_title: Basic Store API
swagger_version: 1.0.0
tables:
- crud:
  - get
  - post
  - put
  - delete
  name: users
- crud:
  - get
  - post
  - put
  - delete
  name: products
- crud:
  - get
  - post
  - put
  - delete
  name: categories
- crud:
  - get
  - post
  - put
  - delete
  name: orders
