database_url: sqlite:////var/folders/4x/q8y1hw0j4zg75lpz9bfyt_3c0000gn/T/tmpalx71xe3.db
enable_swagger: true
swagger_description: Read-only API for viewing store data
swagger_title: Store Data Viewer API
swagger_version: 1.0.0
tables:
- crud:
  - get
  name: users
- crud:
  - get
  name: products
- crud:
  - get
  name: categories
- crud:
  - get
  name: orders
- crud:
  - get
  name: order_items
- crud:
  - get
  name: reviews
- crud:
  - get
  name: settings
