apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lightapi.fullname" . }}-config
  labels:
    {{- include "lightapi.labels" . | nindent 4 }}
data:
  lightapi.yaml: |
{{ .Values.config | toYaml | indent 4 }}
