{{- $genDb := and .Values.database.url (not .Values.database.existingSecret) -}}
{{- $genJwt := and .Values.jwt.secret (not .Values.jwt.existingSecret) -}}
{{- if or $genDb $genJwt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightapi.fullname" . }}
  labels:
    {{- include "lightapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $genDb }}
  {{ .Values.database.urlKey }}: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if $genJwt }}
  {{ .Values.jwt.secretKey }}: {{ .Values.jwt.secret | quote }}
  {{- end }}
{{- end }}
